name: publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source
      uses: actions/checkout@v2
    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Poetry
      run: |
        pip install -U pip
        curl -sSL "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python -
        echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

    - name: Cache dependencies to speed up workflows
      uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run:  |
        poetry config virtualenvs.in-project true
        poetry run pip install -U pip
        poetry install

    - name: Build the webite
      run:  |
        poetry run make dirhtml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      # only on master branch
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/dirhtml
        publish_branch: gh-pages
